services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun   # TUN device for VPN functionality Important: Add this line to your lxc config file lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file 
    ports:
      - 8080:8080 # qBittorrent WebUI
      - 6881:6881 # Standard, forwarded Port wird von Gluetun gesetzt
    volumes:
      - /docker/gluetun:/gluetun
      - /docker/gluetun/config.toml:/gluetun/auth/config.toml # Authentifizierung für ProtonVPN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=your_private_key_here
      - SERVER_COUNTRIES=Netherlands
      - VPN_PORT_FORWARDING=on
      - GLUETUN_HTTP_CONTROL_SERVER_ENABLE=on

    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881    # Anfangswert, Port-Manager überschreibt
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main # Port-Manager
      - GSP_GTN_API_KEY=your_api_key_here #docker run --rm qmcgaw/gluetun genkey
      - GSP_MINIMAL_LOGS=false
    volumes:
      - /docker/qbittorrent:/config
      - /data2:/data2 
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
